"""first migrate

Revision ID: b0b065e0eddd
Revises: b0fc8b4edc20
Create Date: 2019-03-25 16:32:40.637011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b065e0eddd'
down_revision = 'b0fc8b4edc20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('villageID', sa.String(length=6), nullable=True),
    sa.Column('lastName', sa.String(length=30), nullable=True),
    sa.Column('firstName', sa.String(length=30), nullable=True),
    sa.Column('nickName', sa.String(length=30), nullable=True),
    sa.Column('dateJoined', sa.DateTime(), nullable=True),
    sa.Column('certified', sa.Boolean(), nullable=True),
    sa.Column('certificationTrainingDate', sa.Date(), nullable=True),
    sa.Column('homePhone', sa.String(length=14), nullable=True),
    sa.Column('mobilePhone', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_villageID'), 'member', ['villageID'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_villageID'), table_name='member')
    op.drop_table('member')
    # ### end Alembic commands ###
